# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '29cm_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 29cm_iOS

  target '29cm_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '29cm_iOSUITests' do
    # Pods for testing
  end

pod 'Alamofire'
pod 'Kingfisher'


end
